<?php
// example configuration file for vimonline
// copy this file to a file named: site-config.inc
// in this directory. Adjust values to your local
// install

// host running your msql database
$DB_HOST="localhost";
// database user
$DB_USER="scott";
// database passwd
$DB_PASSWD="";
// database name holding vimonline tables
$DB_NAME="vimscripts";

// root of vimonline relative to your apache
// root. If you have apache pointing at htdocs
// of this project the base should be "/"
$BASE = "/vimscripts/htdocs";

?>
